### ISSUE TITLE
captcha invalidates "Use view to create"

### ISSUE THREAD

**Issue by j2l** [saltcorn/captcha#2]
![image](https://user-images.githubusercontent.com/65325/205626674-422fda02-ece8-43d6-a5b3-212e9680f0c4.png)

This time, since captcha is not in a form, it doesn't repeat and you simply can't finalize your view.
So captcha works, but sometimes not where it is needed :smile:

**Comment by glutamate** [comment]
@j2l as a temporary work around, use the breadcrumb links at the top of the screen

**Comment by glutamate** [comment]
This is my punishment for trying to fit a square peg into a round hole. I need to think about how we can implement this properly, I may have to add a few more things in Saltcorn

**Comment by glutamate** [comment]
I think this is now fixed if on https://github.com/saltcorn/saltcorn/pull/1508 and version 0.1.4 of this plug in. I might try to implement hcaptcha to see if the way I've enhanced the Saltcorn plugin API can deal with this.

**Comment by j2l** [comment]
Breadcrumbs are cool indeed!
Also even when not finalizing the edit, it kept the settings.
Thank you again @glutamate
